### ISSUE TITLE
Use a trait instead of extending?

### ISSUE THREAD

**Issue by robclancy** [Waavi/Sanitizer#1]
https://github.com/Waavi/Sanitizer/blob/master/src/Waavi/Sanitizer/Laravel/FormRequest.php

Using that file greatly restricts things, it would be far better to use a trait imo (as an additional option). I am going to be making my own to use instead of extending your class as we already have our own base request class.

**Comment by sildraug** [comment]
Hi Rob,

Thanks for the advice! We've updated the package so that a Trait is avaialble. Check the readme file for details.
