### ISSUE TITLE
I would like to use some kind of "stripTags" function

### ISSUE THREAD

**Issue by smknstd** [Waavi/Sanitizer#10]
I'd expect the library to be able to strip tags as I used to do wiith zend framework (https://framework.zend.com/manual/2.4/en/modules/zend.filter.strip-tags.html). What do you think ?

ref: http://php.net/manual/en/function.strip-tags.php

**Comment by smknstd** [comment]
Just made a PR https://github.com/Waavi/Sanitizer/pull/11

**Comment by sildraug** [comment]
Merged! Will be ready on next release.

**Comment by smknstd** [comment]
😎
