### ISSUE TITLE
I do not get the filtered data back when validation succeeds.

### ISSUE THREAD

**Issue by wotta** [Waavi/Sanitizer#18]
Found this package yesterday and tried to use the example as shown in the [readme](https://github.com/Waavi/Sanitizer#laravel-goodies).

Now I am running into a problem.
When validation succeeds I still get the raw data from the input fields ( not filtered ).

Not sure if this is intentional but it was not what I expected.
I managed to solve this by creating a private function in the form request where I call the sanitizer myself. ( and merge the result of the sanitizer over the request that is coming in ).

Using laravel 5.6.*

**Comment by AdrianHL** [comment]
@concept-core , check issues #14 and #17. The current version of the package does not work with Laravel 5.6. 
@sildraug, any chance to merge the related PRs in the next days? Thanks

**Comment by concept-core** [comment]
@AdrianHL yeah figured as much but decided to make an issue out of it.
Thanks for the reply 👍

**Comment by sildraug** [comment]
@wotta Latest version should fix this.
