### ISSUE TITLE
No filter found by the name of digit

### ISSUE THREAD

**Issue by tsangaris** [Waavi/Sanitizer#28]
Installing Sanitizer via composer [composer require waavi/sanitizer ~1.0 --dev] or [composer require waavi/sanitizer --dev] the Digit class is not included.

I can include it manually but it beats the purpose! :)

**Comment by sildraug** [comment]
Sorry! Forgot to create a release for this feature. It's available from 1.0.9 onward. Composer update should do the trick in an hour or so!
