### ISSUE TITLE
Sanitizing arrays

### ISSUE THREAD

**Issue by vedmant** [Waavi/Sanitizer#4]
Great Idea! It would be nice to add ability to sanitize arrays the way Laravel validator does it, with rules like `'array.*.key' => 'trim|capitalize'`, so it will go through array and sanitize each item.

**Comment by zarianec** [comment]
Hi, @vedmant. For now You can define rules like in Laravel validator. I mean the second part of your example (`'trim|capitalize'`) according to #8. But wildcards is not merged yet #13.
