### ISSUE TITLE
ErrorException Illegal string offset 'name'

### ISSUE THREAD

**Issue by SHSharkar** [Waavi/Sanitizer#48]
ErrorException
`Illegal string offset 'name'`

![Screenshot_1](https://user-images.githubusercontent.com/12555542/68869816-f8f0c580-0723-11ea-9fbb-d28ff294a685.png)

I am not sure if someone checked properly before merging to the master branch. Even the Travis also failing that latest change. Developers should have tested the breakdown issues before merging the commit.

Also, there should have some changelog information if any new options were added or removed.

**Comment by SHSharkar** [comment]
Travis CI: https://travis-ci.org/Waavi/Sanitizer/builds/611842012

**Comment by omarname** [comment]
Did you manage to find a solution ??

**Comment by alariva** [comment]
Agree with the issue. Rollback to `1.0.13` should be enough workaround until it get's solved.

**Comment by alariva** [comment]
https://github.com/Waavi/Sanitizer/commit/73675ac74700005693b05af1085949b256ede508#r35961725

**Comment by Hirbod** [comment]
I can confirm this. 1.0.14 broke my whole application, since validation failes with that error. Reverted back to 1.0.13 and it works again.

**Comment by huglester** [comment]
confirmed. broken. revering back.

**Comment by harrisdt15f** [comment]
I got error also 
"ErrorException: Illegal string offset 'name' in /var/www/jianghu_entertain/vendor/waavi/sanitizer/src/Sanitizer.php:131\nStack trace:\n#0 /var/www/jianghu_entertain/vendor/waavi/sanitizer/src/Sanitizer.php(131): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Illegal string ...', '/var/www/jiangh...', 131, Array)\n#1 /var/www/jianghu_entertain/vendor/waavi/sanitizer/src/Sanitizer.php(167): Waavi\\Sanitizer\\Sanitizer->applyFilter('cast', '[\"10.10.1.10\"]', Array)\n#2 /var/www/jianghu_entertain/vendor/waavi/sanitizer/src/Laravel/SanitizesInput.php(43): Waavi\\Sanitizer\\Sanitizer->sanitize()\n#3 /var/www/jianghu_entertain/app/Http/Requests/BaseFormRequest.php(30): App\\Http\\Requests\\BaseFormRequest->sanitize()\n#4 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): App\\Http\\Requests\\BaseFormRequest->validateResolved()\n#5 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Container/Container.php(1102): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}(Object(App\\Http\\Requests\\Backend\\Headquarters\\GameVendor\\AddRequest), Object(Illuminate\\Foundation\\Application))\n#6 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Container\\Container->fireCallbackArray(Object(App\\Http\\Requests\\Backend\\Headquarters\\GameVendor\\AddRequest), Array)\n#7 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Container/Container.php(1051): Illuminate\\Container\\Container->fireAfterResolvingCallbacks('App\\\\Http\\\\Reques...', Object(App\\Http\\Requests\\Backend\\Headquarters\\GameVendor\\AddRequest))\n#8 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Container/Container.php(701): Illuminate\\Container\\Container->fireResolvingCallbacks('App\\\\Http\\\\Reques...', Object(App\\Http\\Requests\\Backend\\Headquarters\\GameVendor\\AddRequest))\n#9 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Reques...', Array)\n#10 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\\Container\\Container->make('App\\\\Http\\\\Reques...', Array)\n#11 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Reques...')\n#12 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(46): Illuminate\\Routing\\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array)\n#13 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(27): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))\n#14 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(App\\Http\\Controllers\\BackendApi\\Headquarters\\BackendGameVendorController), 'addDo')\n#15 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\BackendApi\\Headquarters\\BackendGameVendorController), 'addDo')\n#16 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()\n#17 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()\n#18 /var/www/jianghu_entertain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130):
